syntax = "proto3";

package spot.v1;

option go_package = "github.com/nullableocean/grpcservices/api/gen/spot/v1;spotv1";

import "models/user.proto";
import "models/market.proto";
import "validate/validate.proto";

service SpotInstrument {
    rpc ViewMarkets(ViewMarketsRequest) returns (ViewMarketsResponse);
    rpc FindMarket(FindMarketRequest) returns (FindMarketResponse);
}

message ViewMarketsResponse {
    repeated models.v1.Market markets = 1;
    string next_page_token = 2;    
}

// ViewMarketsResponse.next_page_token
message ViewMarketsRequest {
    repeated models.v1.UserRole user_roles = 1 [(validate.rules).repeated = {min_items: 0,max_items: 10,unique: true, items: {enum: {defined_only: true, not_in: [0]}}}];
    string page_token = 2 [(validate.rules).string = {ignore_empty: true, max_len: 512}];
    int32 page_size = 3 [(validate.rules).int32 = {gte: 1,lte: 200}];
}

message FindMarketRequest {
    string market_uuid = 1 [(validate.rules).string = {uuid: true}]; 
    repeated models.v1.UserRole user_roles = 2 [(validate.rules).repeated = {min_items: 0,max_items: 10,unique: true, items: {enum: {defined_only: true, not_in: [0]}}}];
}

message FindMarketResponse {
    models.v1.Market market = 1;
}
    