FROM golang:1.25-alpine AS builder

WORKDIR /app/build

# context ../spot for dev

COPY api/ /app/api
COPY pkg/ /app/pkg


COPY spot/go.mod spot/go.sum ./
RUN go mod download

COPY spot/ .
RUN go build -o app ./cmd

FROM alpine:latest

ARG UID
ARG GID

USER ${UID}:${GID}

WORKDIR /app
COPY --from=builder /app/build/app .

CMD ["./app", "--logdir", "./logs", "--seed"]