FROM golang:1.25-alpine AS builder

WORKDIR /app/build

# context ../spot for dev

COPY api/ /app/api
COPY pkg/ /app/pkg


COPY order/go.mod order/go.sum ./
RUN go mod download

COPY order/ .
RUN go build -o app ./cmd

FROM alpine:latest

WORKDIR /app
COPY --from=builder /app//build/app .

CMD ["./app", "--log-path", "./logs/logs.log"]