// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.30.2
// source: spot.proto

package spotpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpotInstrument_ViewMarkets_FullMethodName = "/spotpb.SpotInstrument/ViewMarkets"
)

// SpotInstrumentClient is the client API for SpotInstrument service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpotInstrumentClient interface {
	ViewMarkets(ctx context.Context, in *ViewMarketsRequest, opts ...grpc.CallOption) (*ViewMarketsResponse, error)
}

type spotInstrumentClient struct {
	cc grpc.ClientConnInterface
}

func NewSpotInstrumentClient(cc grpc.ClientConnInterface) SpotInstrumentClient {
	return &spotInstrumentClient{cc}
}

func (c *spotInstrumentClient) ViewMarkets(ctx context.Context, in *ViewMarketsRequest, opts ...grpc.CallOption) (*ViewMarketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewMarketsResponse)
	err := c.cc.Invoke(ctx, SpotInstrument_ViewMarkets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpotInstrumentServer is the server API for SpotInstrument service.
// All implementations must embed UnimplementedSpotInstrumentServer
// for forward compatibility.
type SpotInstrumentServer interface {
	ViewMarkets(context.Context, *ViewMarketsRequest) (*ViewMarketsResponse, error)
	mustEmbedUnimplementedSpotInstrumentServer()
}

// UnimplementedSpotInstrumentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpotInstrumentServer struct{}

func (UnimplementedSpotInstrumentServer) ViewMarkets(context.Context, *ViewMarketsRequest) (*ViewMarketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ViewMarkets not implemented")
}
func (UnimplementedSpotInstrumentServer) mustEmbedUnimplementedSpotInstrumentServer() {}
func (UnimplementedSpotInstrumentServer) testEmbeddedByValue()                        {}

// UnsafeSpotInstrumentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpotInstrumentServer will
// result in compilation errors.
type UnsafeSpotInstrumentServer interface {
	mustEmbedUnimplementedSpotInstrumentServer()
}

func RegisterSpotInstrumentServer(s grpc.ServiceRegistrar, srv SpotInstrumentServer) {
	// If the following call panics, it indicates UnimplementedSpotInstrumentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpotInstrument_ServiceDesc, srv)
}

func _SpotInstrument_ViewMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpotInstrumentServer).ViewMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpotInstrument_ViewMarkets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpotInstrumentServer).ViewMarkets(ctx, req.(*ViewMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpotInstrument_ServiceDesc is the grpc.ServiceDesc for SpotInstrument service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpotInstrument_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spotpb.SpotInstrument",
	HandlerType: (*SpotInstrumentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ViewMarkets",
			Handler:    _SpotInstrument_ViewMarkets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spot.proto",
}
