// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: spot.proto

package spotpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRole int32

const (
	UserRole_USER_ROLE_UNSPECIFIED UserRole = 0
	UserRole_USER_ROLE_GUEST       UserRole = 1
	UserRole_USER_ROLE_VERIFIED    UserRole = 2
	UserRole_USER_ROLE_SELLER      UserRole = 3
	UserRole_USER_ROLE_MODER       UserRole = 4
	UserRole_USER_ROLE_ADMIN       UserRole = 5
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_UNSPECIFIED",
		1: "USER_ROLE_GUEST",
		2: "USER_ROLE_VERIFIED",
		3: "USER_ROLE_SELLER",
		4: "USER_ROLE_MODER",
		5: "USER_ROLE_ADMIN",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_UNSPECIFIED": 0,
		"USER_ROLE_GUEST":       1,
		"USER_ROLE_VERIFIED":    2,
		"USER_ROLE_SELLER":      3,
		"USER_ROLE_MODER":       4,
		"USER_ROLE_ADMIN":       5,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_spot_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_spot_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_spot_proto_rawDescGZIP(), []int{0}
}

type ViewMarketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markets       []*Market              `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsResponse) Reset() {
	*x = ViewMarketsResponse{}
	mi := &file_spot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsResponse) ProtoMessage() {}

func (x *ViewMarketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsResponse.ProtoReflect.Descriptor instead.
func (*ViewMarketsResponse) Descriptor() ([]byte, []int) {
	return file_spot_proto_rawDescGZIP(), []int{0}
}

func (x *ViewMarketsResponse) GetMarkets() []*Market {
	if x != nil {
		return x.Markets
	}
	return nil
}

type ViewMarketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserRoles     []UserRole             `protobuf:"varint,1,rep,packed,name=user_roles,json=userRoles,proto3,enum=spotpb.UserRole" json:"user_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsRequest) Reset() {
	*x = ViewMarketsRequest{}
	mi := &file_spot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsRequest) ProtoMessage() {}

func (x *ViewMarketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsRequest.ProtoReflect.Descriptor instead.
func (*ViewMarketsRequest) Descriptor() ([]byte, []int) {
	return file_spot_proto_rawDescGZIP(), []int{1}
}

func (x *ViewMarketsRequest) GetUserRoles() []UserRole {
	if x != nil {
		return x.UserRoles
	}
	return nil
}

type Market struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_spot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_spot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Market.ProtoReflect.Descriptor instead.
func (*Market) Descriptor() ([]byte, []int) {
	return file_spot_proto_rawDescGZIP(), []int{2}
}

func (x *Market) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Market) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_spot_proto protoreflect.FileDescriptor

const file_spot_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"spot.proto\x12\x06spotpb\"?\n" +
	"\x13ViewMarketsResponse\x12(\n" +
	"\amarkets\x18\x01 \x03(\v2\x0e.spotpb.MarketR\amarkets\"E\n" +
	"\x12ViewMarketsRequest\x12/\n" +
	"\n" +
	"user_roles\x18\x01 \x03(\x0e2\x10.spotpb.UserRoleR\tuserRoles\",\n" +
	"\x06Market\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name*\x92\x01\n" +
	"\bUserRole\x12\x19\n" +
	"\x15USER_ROLE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fUSER_ROLE_GUEST\x10\x01\x12\x16\n" +
	"\x12USER_ROLE_VERIFIED\x10\x02\x12\x14\n" +
	"\x10USER_ROLE_SELLER\x10\x03\x12\x13\n" +
	"\x0fUSER_ROLE_MODER\x10\x04\x12\x13\n" +
	"\x0fUSER_ROLE_ADMIN\x10\x052X\n" +
	"\x0eSpotInstrument\x12F\n" +
	"\vViewMarkets\x12\x1a.spotpb.ViewMarketsRequest\x1a\x1b.spotpb.ViewMarketsResponseB2Z0github.com/nullableocean/grpcservices/api/spotpbb\x06proto3"

var (
	file_spot_proto_rawDescOnce sync.Once
	file_spot_proto_rawDescData []byte
)

func file_spot_proto_rawDescGZIP() []byte {
	file_spot_proto_rawDescOnce.Do(func() {
		file_spot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spot_proto_rawDesc), len(file_spot_proto_rawDesc)))
	})
	return file_spot_proto_rawDescData
}

var file_spot_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spot_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spot_proto_goTypes = []any{
	(UserRole)(0),               // 0: spotpb.UserRole
	(*ViewMarketsResponse)(nil), // 1: spotpb.ViewMarketsResponse
	(*ViewMarketsRequest)(nil),  // 2: spotpb.ViewMarketsRequest
	(*Market)(nil),              // 3: spotpb.Market
}
var file_spot_proto_depIdxs = []int32{
	3, // 0: spotpb.ViewMarketsResponse.markets:type_name -> spotpb.Market
	0, // 1: spotpb.ViewMarketsRequest.user_roles:type_name -> spotpb.UserRole
	2, // 2: spotpb.SpotInstrument.ViewMarkets:input_type -> spotpb.ViewMarketsRequest
	1, // 3: spotpb.SpotInstrument.ViewMarkets:output_type -> spotpb.ViewMarketsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_spot_proto_init() }
func file_spot_proto_init() {
	if File_spot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spot_proto_rawDesc), len(file_spot_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spot_proto_goTypes,
		DependencyIndexes: file_spot_proto_depIdxs,
		EnumInfos:         file_spot_proto_enumTypes,
		MessageInfos:      file_spot_proto_msgTypes,
	}.Build()
	File_spot_proto = out.File
	file_spot_proto_goTypes = nil
	file_spot_proto_depIdxs = nil
}
