syntax = "proto3";

package events.order.v1;

option go_package = "github.com/nullableocean/grpcservices/api/gen/events/order/v1;ordereventsv1";

import "models/order.proto";
import "google/protobuf/timestamp.proto";
import "validate/validate.proto";

// UpdateStatus — событие об изменении статуса ордера
message UpdateStatus {
    // UUID события
    string event_uuid = 1 [(validate.rules).string = {uuid: true}];
    // UUID ордера, у которого изменился статус
    string order_uuid = 2 [(validate.rules).string = {uuid: true}];
    // Новый статус ордера
    models.v1.OrderStatus new_status = 3;
    // Предыдущий статус
    models.v1.OrderStatus old_status = 4;
    // Время создания события
    google.protobuf.Timestamp updated_at = 5;
}
