services:
  broker:
    image: apache/kafka:latest
    container_name: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:9093,DOCKERNET://0.0.0.0:9092,LOCALHOST://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKERNET:PLAINTEXT,CONTROLLER:PLAINTEXT,LOCALHOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: DOCKERNET://broker:9092,LOCALHOST://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKERNET
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093

      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
    ports:
      - "9094:9094"
      - "9092:9092"
    volumes:
      - kafkadata:/var/lib/kafka/data
    networks:
      - brokernet

networks:
    brokernet:
      external: true
      name: brokernet
volumes:
  kafkadata: